{% set name = "pyxel-sim" %}
{% set version = "1.12" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pyxel_sim-{{ version }}.tar.gz
  sha256: 53a56f8eb86419e73cfcc322d6f3ce82c2f1bdef752021c82f87ef648bfe1347

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.9
    - versioneer
    - pip
  run:
    - python >=3.9
    - numba
    - numpy >=1.21
    - pandas
    - scipy
    - xarray >=2022.06
    - xarray-datatree >=0.0.12
    - sep
    - matplotlib-base >=3.1
    - seaborn
    - hvplot
    - bokeh
    - dask-core
    - distributed
    - ipywidgets >=7.5
    - astropy >=4.3
    - fsspec >=2021
    - aiohttp
    - h5py
    - h5netcdf
    - pyyaml
    - xlrd
    - openpyxl
    - netcdf4
    - attrs >=21.3.0
    - click !=8.1.4,!=8.1.5
    - tqdm
    - typing-extensions
    - pympler
    - pillow
    - scikit-image
    - astroquery
    - specutils
    - synphot
    - asdf # Added manually
    - pygmo  >=2.16.1      # Added manually

test:
  imports:
    - pyxel_sim
    - pyxel.calibration
  commands:
    - pip check
    - pyxel --help
  requires:
    - pip

about:
  home: https://esa.gitlab.io/pyxel/
  summary: Pyxel detector simulation framework.
  dev_url: https://gitlab.com/esa/pyxel
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - flemmel
    - constanzeseibert
